name = "og-generator"
main = "src/index.ts"
compatibility_date = "2024-05-20"
compatibility_flags = ["nodejs_compat"]

rules = [
  { type = "Data", globs = ["**/*.ttf"], fallthrough = true }
]

[placement]
mode = "smart"

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#r2-buckets
[[r2_buckets]]
binding = "FONTS"
bucket_name = "fonts"

