name = "og-generator"
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

account_id = "9afa0c9be58a0bb6d2f7d43f6ec2fedb"

[placement]
mode = "smart"

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#r2-buckets
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "test-bucket"
jurisdiction = "eu"

